### ISSUE TITLE
Une exigence

### ISSUE THREAD

**Issue by alagane** [MordecaiXLII/MySimpleStack#3]
Ton stack il devrait avoir une fonction pour supprimer tout les éléments sauf celui tout en bas, et genre si la pile et vide ça renvoie une WTFException !

**Comment by MordecaiXLII** [comment]
Alors au pire, tg. Merci, je vais te casser la gueule espèce de sac à merde. Je te conspue et espère que ton décès sera lent et douloureux.

Cordialement.

Bises, Martine.

**Comment by alagane** [comment]
Ok :(
